# This is a build configuration for travis-ci.org
language: c
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libelf1 libelf-dev libdisasm0 libdisasm-dev libelfg0 libelfg0-dev
script: make
